"""Seed a small starter deck for new users so their first study session isn't empty."""

import audio
import db

# (source_text, target_text, romanization)
_WORDS: dict[str, list[tuple[str, str, str]]] = {
    "yue": [
        ("hello", "你好", "nei5 hou2"),
        ("thank you", "唔該", "m4 goi1"),
        ("yes", "係", "hai6"),
        ("no", "唔係", "m4 hai6"),
        ("I / me", "我", "ngo5"),
        ("you", "你", "nei5"),
        ("good", "好", "hou2"),
        ("eat", "食", "sik6"),
        ("drink", "飲", "jam2"),
        ("water", "水", "seoi2"),
        ("one", "一", "jat1"),
        ("person", "人", "jan4"),
    ],
    "cmn": [
        ("hello", "你好", "nǐ hǎo"),
        ("thank you", "谢谢", "xiè xie"),
        ("please", "请", "qǐng"),
        ("yes", "是", "shì"),
        ("no", "不是", "bù shì"),
        ("I / me", "我", "wǒ"),
        ("you", "你", "nǐ"),
        ("good", "好", "hǎo"),
        ("eat", "吃", "chī"),
        ("drink", "喝", "hē"),
        ("water", "水", "shuǐ"),
        ("one", "一", "yī"),
    ],
    "fr": [
        ("hello", "Bonjour", ""),
        ("thank you", "Merci", ""),
        ("please", "S'il vous plaît", ""),
        ("yes", "Oui", ""),
        ("no", "Non", ""),
        ("I / me", "Je", ""),
        ("you (informal)", "Tu", ""),
        ("good", "Bien", ""),
        ("eat", "Manger", ""),
        ("drink", "Boire", ""),
        ("water", "Eau", ""),
        ("one", "Un", ""),
    ],
    "es": [
        ("hello", "Hola", ""),
        ("thank you", "Gracias", ""),
        ("please", "Por favor", ""),
        ("yes", "Sí", ""),
        ("no", "No", ""),
        ("I / me", "Yo", ""),
        ("you (informal)", "Tú", ""),
        ("good", "Bueno", ""),
        ("eat", "Comer", ""),
        ("drink", "Beber", ""),
        ("water", "Agua", ""),
        ("one", "Uno", ""),
    ],
    "de": [
        ("hello", "Hallo", ""),
        ("thank you", "Danke", ""),
        ("please", "Bitte", ""),
        ("yes", "Ja", ""),
        ("no", "Nein", ""),
        ("I / me", "Ich", ""),
        ("you (informal)", "Du", ""),
        ("good", "Gut", ""),
        ("eat", "Essen", ""),
        ("drink", "Trinken", ""),
        ("water", "Wasser", ""),
        ("one", "Eins", ""),
    ],
    "it": [
        ("hello", "Ciao", ""),
        ("thank you", "Grazie", ""),
        ("please", "Per favore", ""),
        ("yes", "Sì", ""),
        ("no", "No", ""),
        ("I / me", "Io", ""),
        ("you (informal)", "Tu", ""),
        ("good", "Buono", ""),
        ("eat", "Mangiare", ""),
        ("drink", "Bere", ""),
        ("water", "Acqua", ""),
        ("one", "Uno", ""),
    ],
    "pt": [
        ("hello", "Olá", ""),
        ("thank you", "Obrigado", ""),
        ("please", "Por favor", ""),
        ("yes", "Sim", ""),
        ("no", "Não", ""),
        ("I / me", "Eu", ""),
        ("you (informal)", "Você", ""),
        ("good", "Bom", ""),
        ("eat", "Comer", ""),
        ("drink", "Beber", ""),
        ("water", "Água", ""),
        ("one", "Um", ""),
    ],
    "tl": [
        ("hello", "Kumusta", ""),
        ("thank you", "Salamat", ""),
        ("please", "Pakiusap", ""),
        ("yes", "Oo", ""),
        ("no", "Hindi", ""),
        ("I / me", "Ako", ""),
        ("you", "Ikaw", ""),
        ("good", "Mabuti", ""),
        ("eat", "Kumain", ""),
        ("drink", "Uminom", ""),
        ("water", "Tubig", ""),
        ("one", "Isa", ""),
    ],
    "ms": [
        ("hello", "Helo", ""),
        ("thank you", "Terima kasih", ""),
        ("please", "Tolong", ""),
        ("yes", "Ya", ""),
        ("no", "Tidak", ""),
        ("I / me", "Saya", ""),
        ("you", "Awak", ""),
        ("good", "Bagus", ""),
        ("eat", "Makan", ""),
        ("drink", "Minum", ""),
        ("water", "Air", ""),
        ("one", "Satu", ""),
    ],
    "id": [
        ("hello", "Halo", ""),
        ("thank you", "Terima kasih", ""),
        ("please", "Tolong", ""),
        ("yes", "Ya", ""),
        ("no", "Tidak", ""),
        ("I / me", "Saya", ""),
        ("you", "Kamu", ""),
        ("good", "Bagus", ""),
        ("eat", "Makan", ""),
        ("drink", "Minum", ""),
        ("water", "Air", ""),
        ("one", "Satu", ""),
    ],
    "ko": [
        ("hello", "안녕하세요", "annyeonghaseyo"),
        ("thank you", "감사합니다", "gamsahamnida"),
        ("yes", "네", "ne"),
        ("no", "아니요", "aniyo"),
        ("I / me", "저", "jeo"),
        ("you (informal)", "너", "neo"),
        ("good", "좋다", "jota"),
        ("eat", "먹다", "meokda"),
        ("drink", "마시다", "masida"),
        ("water", "물", "mul"),
        ("one", "하나", "hana"),
        ("person", "사람", "saram"),
    ],
    "hi": [
        ("hello", "नमस्ते", "namaste"),
        ("thank you", "धन्यवाद", "dhanyavāda"),
        ("yes", "हाँ", "hāṁ"),
        ("no", "नहीं", "nahīṃ"),
        ("I / me", "मैं", "maiṃ"),
        ("you (informal)", "तुम", "tuma"),
        ("good", "अच्छा", "acchā"),
        ("eat", "खाना", "khānā"),
        ("drink", "पीना", "pīnā"),
        ("water", "पानी", "pānī"),
        ("one", "एक", "eka"),
        ("person", "आदमी", "ādamī"),
    ],
}


async def seed(user_id: int, lang: str) -> None:
    """Create starter cards for user if they have no cards yet. Best-effort."""
    words = _WORDS.get(lang)
    if not words:
        return
    if await db.count_cards(user_id) > 0:
        return
    label_id = await db.get_or_create_label(user_id, "🌱 Starter")
    for source, target, roman in words:
        try:
            audio_data = await audio.generate(target, lang)
            await db.create_card(
                user_id=user_id,
                source_text=source,
                target_text=target,
                romanization=roman,
                target_lang=lang,
                audio_data=audio_data,
                priority=3,
                label_ids=[label_id],
            )
        except Exception:
            pass
